#! /bin/sh

sxhkd 2>&1 > ~/.config/sxhkd/logs &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width            2
bspc config window_gap              8

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         false

bspc config normal_border_color     "#31535b"
bspc config active_border_color     "#55b5db"
bspc config focused_border_color    "#55b5db"
bspc config presel-feedback-color   "#55b5db"

bspc rule -a Gimp                   state=floating follow=on
bspc rule -a "*:galculator"         state=floating follow=on
bspc rule -a "*:pavucontrol"        state=floating follow=on
bspc rule -a "*:xev"                state=floating follow=on
bspc rule -a Screenkey              manage=off
