#!/bin/sh

if [ -x "$(which stack)" ]
then
    stack exec ghc -- \
        --make xmonad.hs \
        -i \
        -ilib \
        -fforce-recomp \
        -main-is main \
        -v0 \
        -o "$1"
else
    docker run \
        --rm \
        -v /home/jtdubs/.xmonad:/home/user/.xmonad \
        -h xmonad \
        -t xmonad:0.1 \
        xmonad --recompile
fi
